#!/usr/bin/env node

import "./config/env.js";

import { Command } from "commander";
import chalk from "chalk";
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import inquirer from "inquirer";
import path from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const program = new Command();

program.name("claw").description("Purrfect Claws CLI").version("1.0.0");

const commandsDir = path.join(__dirname, "commands");
const commandFiles = fs
  .readdirSync(commandsDir)
  .filter((file) => file.endsWith(".js"));

for (const file of commandFiles) {
  const registerCommand = await import(path.join(commandsDir, file)).then(
    (m) => m.default,
  );
  registerCommand(program, inquirer, chalk);
}

program.parse(process.argv);
