export var LoadMoreDirection;
(function (LoadMoreDirection) {
    LoadMoreDirection[LoadMoreDirection["Backwards"] = 0] = "Backwards";
    LoadMoreDirection[LoadMoreDirection["Forwards"] = 1] = "Forwards";
    LoadMoreDirection[LoadMoreDirection["Around"] = 2] = "Around";
})(LoadMoreDirection || (LoadMoreDirection = {}));
export var FocusDirection;
(function (FocusDirection) {
    FocusDirection[FocusDirection["Up"] = 0] = "Up";
    FocusDirection[FocusDirection["Down"] = 1] = "Down";
    FocusDirection[FocusDirection["Static"] = 2] = "Static";
})(FocusDirection || (FocusDirection = {}));
export var SettingsScreens;
(function (SettingsScreens) {
    SettingsScreens[SettingsScreens["Main"] = 0] = "Main";
    SettingsScreens[SettingsScreens["EditProfile"] = 1] = "EditProfile";
    SettingsScreens[SettingsScreens["Notifications"] = 2] = "Notifications";
    SettingsScreens[SettingsScreens["DataStorage"] = 3] = "DataStorage";
    SettingsScreens[SettingsScreens["Language"] = 4] = "Language";
    SettingsScreens[SettingsScreens["ActiveSessions"] = 5] = "ActiveSessions";
    SettingsScreens[SettingsScreens["General"] = 6] = "General";
    SettingsScreens[SettingsScreens["GeneralChatBackground"] = 7] = "GeneralChatBackground";
    SettingsScreens[SettingsScreens["GeneralChatBackgroundColor"] = 8] = "GeneralChatBackgroundColor";
    SettingsScreens[SettingsScreens["Privacy"] = 9] = "Privacy";
    SettingsScreens[SettingsScreens["PrivacyPhoneNumber"] = 10] = "PrivacyPhoneNumber";
    SettingsScreens[SettingsScreens["PrivacyAddByPhone"] = 11] = "PrivacyAddByPhone";
    SettingsScreens[SettingsScreens["PrivacyLastSeen"] = 12] = "PrivacyLastSeen";
    SettingsScreens[SettingsScreens["PrivacyProfilePhoto"] = 13] = "PrivacyProfilePhoto";
    SettingsScreens[SettingsScreens["PrivacyBio"] = 14] = "PrivacyBio";
    SettingsScreens[SettingsScreens["PrivacyBirthday"] = 15] = "PrivacyBirthday";
    SettingsScreens[SettingsScreens["PrivacyGifts"] = 16] = "PrivacyGifts";
    SettingsScreens[SettingsScreens["PrivacyPhoneCall"] = 17] = "PrivacyPhoneCall";
    SettingsScreens[SettingsScreens["PrivacyPhoneP2P"] = 18] = "PrivacyPhoneP2P";
    SettingsScreens[SettingsScreens["PrivacyForwarding"] = 19] = "PrivacyForwarding";
    SettingsScreens[SettingsScreens["PrivacyVoiceMessages"] = 20] = "PrivacyVoiceMessages";
    SettingsScreens[SettingsScreens["PrivacyMessages"] = 21] = "PrivacyMessages";
    SettingsScreens[SettingsScreens["PrivacyGroupChats"] = 22] = "PrivacyGroupChats";
    SettingsScreens[SettingsScreens["PrivacyPhoneNumberAllowedContacts"] = 23] = "PrivacyPhoneNumberAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyPhoneNumberDeniedContacts"] = 24] = "PrivacyPhoneNumberDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyLastSeenAllowedContacts"] = 25] = "PrivacyLastSeenAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyLastSeenDeniedContacts"] = 26] = "PrivacyLastSeenDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyProfilePhotoAllowedContacts"] = 27] = "PrivacyProfilePhotoAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyProfilePhotoDeniedContacts"] = 28] = "PrivacyProfilePhotoDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyBioAllowedContacts"] = 29] = "PrivacyBioAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyBioDeniedContacts"] = 30] = "PrivacyBioDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyBirthdayAllowedContacts"] = 31] = "PrivacyBirthdayAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyBirthdayDeniedContacts"] = 32] = "PrivacyBirthdayDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyGiftsAllowedContacts"] = 33] = "PrivacyGiftsAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyGiftsDeniedContacts"] = 34] = "PrivacyGiftsDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyPhoneCallAllowedContacts"] = 35] = "PrivacyPhoneCallAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyPhoneCallDeniedContacts"] = 36] = "PrivacyPhoneCallDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyPhoneP2PAllowedContacts"] = 37] = "PrivacyPhoneP2PAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyPhoneP2PDeniedContacts"] = 38] = "PrivacyPhoneP2PDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyForwardingAllowedContacts"] = 39] = "PrivacyForwardingAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyForwardingDeniedContacts"] = 40] = "PrivacyForwardingDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyVoiceMessagesAllowedContacts"] = 41] = "PrivacyVoiceMessagesAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyVoiceMessagesDeniedContacts"] = 42] = "PrivacyVoiceMessagesDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyGroupChatsAllowedContacts"] = 43] = "PrivacyGroupChatsAllowedContacts";
    SettingsScreens[SettingsScreens["PrivacyGroupChatsDeniedContacts"] = 44] = "PrivacyGroupChatsDeniedContacts";
    SettingsScreens[SettingsScreens["PrivacyBlockedUsers"] = 45] = "PrivacyBlockedUsers";
    SettingsScreens[SettingsScreens["PrivacyNoPaidMessages"] = 46] = "PrivacyNoPaidMessages";
    SettingsScreens[SettingsScreens["Performance"] = 47] = "Performance";
    SettingsScreens[SettingsScreens["Folders"] = 48] = "Folders";
    SettingsScreens[SettingsScreens["FoldersCreateFolder"] = 49] = "FoldersCreateFolder";
    SettingsScreens[SettingsScreens["FoldersEditFolder"] = 50] = "FoldersEditFolder";
    SettingsScreens[SettingsScreens["FoldersEditFolderFromChatList"] = 51] = "FoldersEditFolderFromChatList";
    SettingsScreens[SettingsScreens["FoldersEditFolderInvites"] = 52] = "FoldersEditFolderInvites";
    SettingsScreens[SettingsScreens["FoldersIncludedChats"] = 53] = "FoldersIncludedChats";
    SettingsScreens[SettingsScreens["FoldersIncludedChatsFromChatList"] = 54] = "FoldersIncludedChatsFromChatList";
    SettingsScreens[SettingsScreens["FoldersExcludedChats"] = 55] = "FoldersExcludedChats";
    SettingsScreens[SettingsScreens["FoldersExcludedChatsFromChatList"] = 56] = "FoldersExcludedChatsFromChatList";
    SettingsScreens[SettingsScreens["TwoFaDisabled"] = 57] = "TwoFaDisabled";
    SettingsScreens[SettingsScreens["TwoFaNewPassword"] = 58] = "TwoFaNewPassword";
    SettingsScreens[SettingsScreens["TwoFaNewPasswordConfirm"] = 59] = "TwoFaNewPasswordConfirm";
    SettingsScreens[SettingsScreens["TwoFaNewPasswordHint"] = 60] = "TwoFaNewPasswordHint";
    SettingsScreens[SettingsScreens["TwoFaNewPasswordEmail"] = 61] = "TwoFaNewPasswordEmail";
    SettingsScreens[SettingsScreens["TwoFaNewPasswordEmailCode"] = 62] = "TwoFaNewPasswordEmailCode";
    SettingsScreens[SettingsScreens["TwoFaEnabled"] = 63] = "TwoFaEnabled";
    SettingsScreens[SettingsScreens["TwoFaChangePasswordCurrent"] = 64] = "TwoFaChangePasswordCurrent";
    SettingsScreens[SettingsScreens["TwoFaChangePasswordNew"] = 65] = "TwoFaChangePasswordNew";
    SettingsScreens[SettingsScreens["TwoFaChangePasswordConfirm"] = 66] = "TwoFaChangePasswordConfirm";
    SettingsScreens[SettingsScreens["TwoFaChangePasswordHint"] = 67] = "TwoFaChangePasswordHint";
    SettingsScreens[SettingsScreens["TwoFaTurnOff"] = 68] = "TwoFaTurnOff";
    SettingsScreens[SettingsScreens["TwoFaRecoveryEmailCurrentPassword"] = 69] = "TwoFaRecoveryEmailCurrentPassword";
    SettingsScreens[SettingsScreens["TwoFaRecoveryEmail"] = 70] = "TwoFaRecoveryEmail";
    SettingsScreens[SettingsScreens["TwoFaRecoveryEmailCode"] = 71] = "TwoFaRecoveryEmailCode";
    SettingsScreens[SettingsScreens["TwoFaCongratulations"] = 72] = "TwoFaCongratulations";
    SettingsScreens[SettingsScreens["ActiveWebsites"] = 73] = "ActiveWebsites";
    SettingsScreens[SettingsScreens["PasscodeDisabled"] = 74] = "PasscodeDisabled";
    SettingsScreens[SettingsScreens["PasscodeNewPasscode"] = 75] = "PasscodeNewPasscode";
    SettingsScreens[SettingsScreens["PasscodeNewPasscodeConfirm"] = 76] = "PasscodeNewPasscodeConfirm";
    SettingsScreens[SettingsScreens["PasscodeEnabled"] = 77] = "PasscodeEnabled";
    SettingsScreens[SettingsScreens["PasscodeChangePasscodeCurrent"] = 78] = "PasscodeChangePasscodeCurrent";
    SettingsScreens[SettingsScreens["PasscodeChangePasscodeNew"] = 79] = "PasscodeChangePasscodeNew";
    SettingsScreens[SettingsScreens["PasscodeChangePasscodeConfirm"] = 80] = "PasscodeChangePasscodeConfirm";
    SettingsScreens[SettingsScreens["PasscodeTurnOff"] = 81] = "PasscodeTurnOff";
    SettingsScreens[SettingsScreens["PasscodeCongratulations"] = 82] = "PasscodeCongratulations";
    SettingsScreens[SettingsScreens["Experimental"] = 83] = "Experimental";
    SettingsScreens[SettingsScreens["Stickers"] = 84] = "Stickers";
    SettingsScreens[SettingsScreens["QuickReaction"] = 85] = "QuickReaction";
    SettingsScreens[SettingsScreens["CustomEmoji"] = 86] = "CustomEmoji";
    SettingsScreens[SettingsScreens["DoNotTranslate"] = 87] = "DoNotTranslate";
    SettingsScreens[SettingsScreens["FoldersShare"] = 88] = "FoldersShare";
})(SettingsScreens || (SettingsScreens = {}));
export var LeftColumnContent;
(function (LeftColumnContent) {
    LeftColumnContent[LeftColumnContent["ChatList"] = 0] = "ChatList";
    LeftColumnContent[LeftColumnContent["GlobalSearch"] = 1] = "GlobalSearch";
    LeftColumnContent[LeftColumnContent["Settings"] = 2] = "Settings";
    LeftColumnContent[LeftColumnContent["Contacts"] = 3] = "Contacts";
    LeftColumnContent[LeftColumnContent["Archived"] = 4] = "Archived";
    LeftColumnContent[LeftColumnContent["NewChannelStep1"] = 5] = "NewChannelStep1";
    LeftColumnContent[LeftColumnContent["NewChannelStep2"] = 6] = "NewChannelStep2";
    LeftColumnContent[LeftColumnContent["NewGroupStep1"] = 7] = "NewGroupStep1";
    LeftColumnContent[LeftColumnContent["NewGroupStep2"] = 8] = "NewGroupStep2";
})(LeftColumnContent || (LeftColumnContent = {}));
export var GlobalSearchContent;
(function (GlobalSearchContent) {
    GlobalSearchContent[GlobalSearchContent["ChatList"] = 0] = "ChatList";
    GlobalSearchContent[GlobalSearchContent["ChannelList"] = 1] = "ChannelList";
    GlobalSearchContent[GlobalSearchContent["BotApps"] = 2] = "BotApps";
    GlobalSearchContent[GlobalSearchContent["Media"] = 3] = "Media";
    GlobalSearchContent[GlobalSearchContent["Links"] = 4] = "Links";
    GlobalSearchContent[GlobalSearchContent["Files"] = 5] = "Files";
    GlobalSearchContent[GlobalSearchContent["Music"] = 6] = "Music";
    GlobalSearchContent[GlobalSearchContent["Voice"] = 7] = "Voice";
})(GlobalSearchContent || (GlobalSearchContent = {}));
export var RightColumnContent;
(function (RightColumnContent) {
    RightColumnContent[RightColumnContent["ChatInfo"] = 0] = "ChatInfo";
    RightColumnContent[RightColumnContent["Management"] = 1] = "Management";
    RightColumnContent[RightColumnContent["Statistics"] = 2] = "Statistics";
    RightColumnContent[RightColumnContent["BoostStatistics"] = 3] = "BoostStatistics";
    RightColumnContent[RightColumnContent["MessageStatistics"] = 4] = "MessageStatistics";
    RightColumnContent[RightColumnContent["StoryStatistics"] = 5] = "StoryStatistics";
    RightColumnContent[RightColumnContent["StickerSearch"] = 6] = "StickerSearch";
    RightColumnContent[RightColumnContent["GifSearch"] = 7] = "GifSearch";
    RightColumnContent[RightColumnContent["PollResults"] = 8] = "PollResults";
    RightColumnContent[RightColumnContent["AddingMembers"] = 9] = "AddingMembers";
    RightColumnContent[RightColumnContent["CreateTopic"] = 10] = "CreateTopic";
    RightColumnContent[RightColumnContent["EditTopic"] = 11] = "EditTopic";
    RightColumnContent[RightColumnContent["MonetizationStatistics"] = 12] = "MonetizationStatistics";
    RightColumnContent[RightColumnContent["NewGroup"] = 13] = "NewGroup";
})(RightColumnContent || (RightColumnContent = {}));
export var MediaViewerOrigin;
(function (MediaViewerOrigin) {
    MediaViewerOrigin[MediaViewerOrigin["Inline"] = 0] = "Inline";
    MediaViewerOrigin[MediaViewerOrigin["ScheduledInline"] = 1] = "ScheduledInline";
    MediaViewerOrigin[MediaViewerOrigin["SharedMedia"] = 2] = "SharedMedia";
    MediaViewerOrigin[MediaViewerOrigin["ProfileAvatar"] = 3] = "ProfileAvatar";
    MediaViewerOrigin[MediaViewerOrigin["SettingsAvatar"] = 4] = "SettingsAvatar";
    MediaViewerOrigin[MediaViewerOrigin["MiddleHeaderAvatar"] = 5] = "MiddleHeaderAvatar";
    MediaViewerOrigin[MediaViewerOrigin["Album"] = 6] = "Album";
    MediaViewerOrigin[MediaViewerOrigin["ScheduledAlbum"] = 7] = "ScheduledAlbum";
    MediaViewerOrigin[MediaViewerOrigin["SearchResult"] = 8] = "SearchResult";
    MediaViewerOrigin[MediaViewerOrigin["ChannelAvatar"] = 9] = "ChannelAvatar";
    MediaViewerOrigin[MediaViewerOrigin["SuggestedAvatar"] = 10] = "SuggestedAvatar";
    MediaViewerOrigin[MediaViewerOrigin["StarsTransaction"] = 11] = "StarsTransaction";
    MediaViewerOrigin[MediaViewerOrigin["PreviewMedia"] = 12] = "PreviewMedia";
    MediaViewerOrigin[MediaViewerOrigin["SponsoredMessage"] = 13] = "SponsoredMessage";
})(MediaViewerOrigin || (MediaViewerOrigin = {}));
export var StoryViewerOrigin;
(function (StoryViewerOrigin) {
    StoryViewerOrigin[StoryViewerOrigin["StoryRibbon"] = 0] = "StoryRibbon";
    StoryViewerOrigin[StoryViewerOrigin["MiddleHeaderAvatar"] = 1] = "MiddleHeaderAvatar";
    StoryViewerOrigin[StoryViewerOrigin["ChatList"] = 2] = "ChatList";
    StoryViewerOrigin[StoryViewerOrigin["SearchResult"] = 3] = "SearchResult";
})(StoryViewerOrigin || (StoryViewerOrigin = {}));
export var AudioOrigin;
(function (AudioOrigin) {
    AudioOrigin[AudioOrigin["Inline"] = 0] = "Inline";
    AudioOrigin[AudioOrigin["SharedMedia"] = 1] = "SharedMedia";
    AudioOrigin[AudioOrigin["Search"] = 2] = "Search";
    AudioOrigin[AudioOrigin["OneTimeModal"] = 3] = "OneTimeModal";
})(AudioOrigin || (AudioOrigin = {}));
export var ChatCreationProgress;
(function (ChatCreationProgress) {
    ChatCreationProgress[ChatCreationProgress["Idle"] = 0] = "Idle";
    ChatCreationProgress[ChatCreationProgress["InProgress"] = 1] = "InProgress";
    ChatCreationProgress[ChatCreationProgress["Complete"] = 2] = "Complete";
    ChatCreationProgress[ChatCreationProgress["Error"] = 3] = "Error";
})(ChatCreationProgress || (ChatCreationProgress = {}));
export var ProfileEditProgress;
(function (ProfileEditProgress) {
    ProfileEditProgress[ProfileEditProgress["Idle"] = 0] = "Idle";
    ProfileEditProgress[ProfileEditProgress["InProgress"] = 1] = "InProgress";
    ProfileEditProgress[ProfileEditProgress["Complete"] = 2] = "Complete";
    ProfileEditProgress[ProfileEditProgress["Error"] = 3] = "Error";
})(ProfileEditProgress || (ProfileEditProgress = {}));
export var ManagementProgress;
(function (ManagementProgress) {
    ManagementProgress[ManagementProgress["Idle"] = 0] = "Idle";
    ManagementProgress[ManagementProgress["InProgress"] = 1] = "InProgress";
    ManagementProgress[ManagementProgress["Complete"] = 2] = "Complete";
    ManagementProgress[ManagementProgress["Error"] = 3] = "Error";
})(ManagementProgress || (ManagementProgress = {}));
export var NewChatMembersProgress;
(function (NewChatMembersProgress) {
    NewChatMembersProgress[NewChatMembersProgress["Closed"] = 0] = "Closed";
    NewChatMembersProgress[NewChatMembersProgress["InProgress"] = 1] = "InProgress";
    NewChatMembersProgress[NewChatMembersProgress["Loading"] = 2] = "Loading";
})(NewChatMembersProgress || (NewChatMembersProgress = {}));
export var ProfileState;
(function (ProfileState) {
    ProfileState[ProfileState["Profile"] = 0] = "Profile";
    ProfileState[ProfileState["SharedMedia"] = 1] = "SharedMedia";
    ProfileState[ProfileState["MemberList"] = 2] = "MemberList";
    ProfileState[ProfileState["GiftList"] = 3] = "GiftList";
    ProfileState[ProfileState["StoryList"] = 4] = "StoryList";
    ProfileState[ProfileState["SavedDialogs"] = 5] = "SavedDialogs";
})(ProfileState || (ProfileState = {}));
export var PaymentStep;
(function (PaymentStep) {
    PaymentStep[PaymentStep["Checkout"] = 0] = "Checkout";
    PaymentStep[PaymentStep["SavedPayments"] = 1] = "SavedPayments";
    PaymentStep[PaymentStep["ConfirmPassword"] = 2] = "ConfirmPassword";
    PaymentStep[PaymentStep["PaymentInfo"] = 3] = "PaymentInfo";
    PaymentStep[PaymentStep["ShippingInfo"] = 4] = "ShippingInfo";
    PaymentStep[PaymentStep["Shipping"] = 5] = "Shipping";
    PaymentStep[PaymentStep["ConfirmPayment"] = 6] = "ConfirmPayment";
})(PaymentStep || (PaymentStep = {}));
export const UPLOADING_WALLPAPER_SLUG = 'UPLOADING_WALLPAPER_SLUG';
export var ManagementScreens;
(function (ManagementScreens) {
    ManagementScreens[ManagementScreens["Initial"] = 0] = "Initial";
    ManagementScreens[ManagementScreens["ChatPrivacyType"] = 1] = "ChatPrivacyType";
    ManagementScreens[ManagementScreens["Discussion"] = 2] = "Discussion";
    ManagementScreens[ManagementScreens["ChannelSubscribers"] = 3] = "ChannelSubscribers";
    ManagementScreens[ManagementScreens["GroupType"] = 4] = "GroupType";
    ManagementScreens[ManagementScreens["GroupPermissions"] = 5] = "GroupPermissions";
    ManagementScreens[ManagementScreens["GroupRemovedUsers"] = 6] = "GroupRemovedUsers";
    ManagementScreens[ManagementScreens["ChannelRemovedUsers"] = 7] = "ChannelRemovedUsers";
    ManagementScreens[ManagementScreens["GroupUserPermissionsCreate"] = 8] = "GroupUserPermissionsCreate";
    ManagementScreens[ManagementScreens["GroupUserPermissions"] = 9] = "GroupUserPermissions";
    ManagementScreens[ManagementScreens["ChatAdministrators"] = 10] = "ChatAdministrators";
    ManagementScreens[ManagementScreens["GroupRecentActions"] = 11] = "GroupRecentActions";
    ManagementScreens[ManagementScreens["ChatAdminRights"] = 12] = "ChatAdminRights";
    ManagementScreens[ManagementScreens["ChatNewAdminRights"] = 13] = "ChatNewAdminRights";
    ManagementScreens[ManagementScreens["GroupMembers"] = 14] = "GroupMembers";
    ManagementScreens[ManagementScreens["GroupAddAdmins"] = 15] = "GroupAddAdmins";
    ManagementScreens[ManagementScreens["Invites"] = 16] = "Invites";
    ManagementScreens[ManagementScreens["EditInvite"] = 17] = "EditInvite";
    ManagementScreens[ManagementScreens["Reactions"] = 18] = "Reactions";
    ManagementScreens[ManagementScreens["InviteInfo"] = 19] = "InviteInfo";
    ManagementScreens[ManagementScreens["JoinRequests"] = 20] = "JoinRequests";
    ManagementScreens[ManagementScreens["NewDiscussionGroup"] = 21] = "NewDiscussionGroup";
})(ManagementScreens || (ManagementScreens = {}));
