const defaultSettings = {
  farmerTitle: "TGUser",
  syncServer: "127.0.0.1:7777",
  closeOtherBots: true,
  showLinksAsGrid: true,
  farmersPerWindow: 5,
  farmerPosition: 1,
  openFarmerInNewWindow: true,
  openFarmerOnStartup: false,
  closeMainWindowOnStartup: false,
  preferredTelegramWebVersion: "k",
  zoomies: [
    "matchquest",
    "notgram",
    "notpixel",
    "blum",
    "hrum",
    "yescoin",
    "wonton",
    "tomarket",
    "pumpad",
    "slotcoin",
    "agent301",
    "goats",
    "truecoin",
    "birdton",
  ],
  repeatZoomiesCycle: true,
};

export default defaultSettings;
